import { CitizenProfile, createEmptyProfile } from '@/types/engine';

export const demoPersonas: Record<string, CitizenProfile> = {
  student: {
    ...createEmptyProfile(),
    name: 'Rohit Sharma',
    age: 19,
    gender: 'Male',
    state: 'Rajasthan',
    district: 'Jaipur',
    annualIncome: 200000,
    category: 'General',
    disability: 'None',
    maritalStatus: 'Single',
    occupation: 'Student',
    education: '12th',
    course: 'B.Tech',
    institution: 'MNIT Jaipur',
    familySize: 4,
    lifeEvents: ['new_student'],
    availableDocuments: ['aadhaar'],
    rawContext: 'I am a 19 year old student from Jaipur, currently doing B.Tech. My family income is 2 lakhs.',
    lastUpdated: new Date().toISOString(),
  },
  farmer: {
    ...createEmptyProfile(),
    name: 'Ramesh Patel',
    age: 45,
    gender: 'Male',
    state: 'Gujarat',
    district: 'Surat',
    annualIncome: 150000,
    category: 'OBC',
    disability: 'None',
    maritalStatus: 'Married',
    occupation: 'Farmer',
    landHolding: 3,
    education: '10th',
    familySize: 5,
    lifeEvents: ['crop_damage'],
    availableDocuments: ['aadhaar', 'land_record'],
    rawContext: 'Farmer from Surat with 3 acres of land. Suffered crop damage recently.',
    lastUpdated: new Date().toISOString(),
  },
  senior: {
    ...createEmptyProfile(),
    name: 'Savitri Devi',
    age: 68,
    gender: 'Female',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    annualIncome: 45000,
    category: 'SC',
    disability: 'None',
    maritalStatus: 'Widowed',
    occupation: 'Retired',
    education: 'None',
    familySize: 1,
    lifeEvents: [],
    availableDocuments: ['aadhaar'],
    rawContext: '68 year old widow from Lucknow living alone.',
    lastUpdated: new Date().toISOString(),
  }
};
